### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by jan-janssen** [MaterialsDiscovery/PyChemia#21]
Hi, 

I recently create the `pychemia` conda forge package, now it is possible to install 
PyChemia via:
```
conda install -c conda-forge pychemia
```
I was wondering if one of the core developers is interested in joining me in maintaining the package. 

Best, 

Jan

**Comment by guilleaf** [comment]
Hello,

That is wonderful, thank you very much, yes, I am interested in maintaining the package, 
can you point me to a good source for the proper way of doing it. So far I just keep it in Pypi but conda is a very needed addition. 

I am basically a coda user, never create a package for it.

Best,

**Comment by jan-janssen** [comment]
Hi @guilleaf, 

I added you to https://github.com/conda-forge/pychemia-feedstock you should get a separate Invitation via Email. In conda-forge most of the mainlining is already automated based on the pip packages. Whenever a new package is released on pip there is an automated pull request. So I suggest we discuss the details once the next version of PyChemia is released. 

Best, 

Jan
